STATION:
  latitude: 41.56
  longitude: -72.66
  name: Van Vleck Observatory
EMERGENCY_CONTACT:
  name: Ivy Huang
  email: ihuang@wesleyan.edu
  phone_number: use email
AZLIMITS:
  lower_bound: 1.0
  upper_bound: 359.0
ELLIMITS:
  lower_bound: 0.0
  upper_bound: 89.0
STOW_LOCATION:
  azimuth: 8.0
  elevation: 8.0
CAL_LOCATION:
  azimuth: 120.0
  elevation: 70.0
HORIZON_POINTS:
  - azimuth: 0
    elevation: 0
  - azimuth: 120
    elevation: 5
  - azimuth: 240
    elevation: 5
  - azimuth: 360
    elevation: 0
MOTOR_TYPE: NONE
MOTOR_PORT: /dev/ttyUSB0
MOTOR_BAUDRATE: 460800
RADIO_CF: 1420000000
RADIO_SF: 2400000
RADIO_FREQ_CORR: -50000
RADIO_NUM_BINS: 256
RADIO_INTEG_CYCLES: 10000
RADIO_AUTOSTART: Yes
NUM_BEAMSWITCHES: 25
BEAMWIDTH: 7.0
TSYS: 171
TCAL: 290
SAVE_DIRECTORY: ~/Desktop/SRT-Saves
RUN_HEADLESS: No
DASHBOARD_PORT: 8080
DASHBOARD_HOST: 127.0.0.1
DASHBOARD_DOWNLOADS: Yes
DASHBOARD_REFRESH_MS: 1000
